### ISSUE TITLE
Name or Service not Known

### ISSUE THREAD

**Issue by Mstpyt** [AxForest/teamspeak_bot#1]
Hi AxForest,

i got an issue with your code and i can't find the problem:

2019-07-10 06:09:11 - root - INFO - Registered command.api_key
2019-07-10 06:09:11 - root - INFO - Registered command.guild
2019-07-10 06:09:11 - root - INFO - Registered command.help
2019-07-10 06:09:11 - root - INFO - Registered command.ignore
2019-07-10 06:09:11 - root - INFO - Registered command.info
2019-07-10 06:09:11 - root - INFO - Registered command.list_group_members
2019-07-10 06:09:11 - root - INFO - Registered command.verify
2019-07-10 06:09:11 - ts3.query - INFO - Created connection to telnet://user:passwd@ts.wvwdzagonur.de:None.
2019-07-10 06:09:11 - ts3.query - INFO - Created connection to telnet://user:passwd@ts.wvwdzagonur.de:10011:<object object at 0x7f8591f9b0c0>.
2019-07-10 06:09:11 - socket - INFO - Created connection to telnet://user:passwd@ts.wvwdzagonur.de:10011.
2019-07-10 06:09:11 - socket - INFO - Created connection to telnet://user:passwd@ts.wvwdzagonur.de:10011:0:1:0:0.
Traceback (most recent call last):
  File "bot.py", line 121, in <module>
    Bot().loop()
  File "bot.py", line 32, in __init__
    config.QUERY_HOST,
  File "/usr/local/lib/python3.5/dist-packages/ts3/query.py", line 181, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.5/dist-packages/ts3/query.py", line 239, in open
    self._telnet_conn = telnetlib.Telnet(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.5/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.5/socket.py", line 696, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 736, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by Mstpyt** [comment]
Nach richtiger Installation von allen Komponenten hat die Verbindung funktioniert.
